# The tidyverse

The tidyverse is not just a collection of packages, or a set of tools; the tidyverse represents a vision, almost a philosophy of how to work with data. The basics are pretty simple, the nuances are pretty complex; so I figured it was worth writing a little bit about.

::: {#book-tip-R-data-science .callout-note}
The book R for Data Science [@Wickham.etal2023] is fully based on tidyverse best practices.
:::

The packages that I use all the time from the tidyverse are dplyr, ggplot2, tibble, and forcats. The non-standard packages (the ones that are not included in `library(tidyverse)` that are in my standard toolset are haven and lubridate.

## Dplyr

There are so many good resources on dplyr, so I won't write too much about that, but just jot down a few notes on functions that I didn't discover until I had already done the same thing by hand many many times before. These are:

-   `count()` and `tally()`. The same can be done with `group_by()` followed by a `summarize(n = n())` but the standard functions are just so much shorter.

-   The `.by` argument in `summarize()` instead of preceding the summarize function with a group_by().

## Visualization

A sample figure made with the tidyverse is @fig-palmer-scatter .

```{r}
#| label: fig-palmer-scatter
#| fig-cap: "Scatterplot of body mass and flipper length for the penguin dataset"

library(palmerpenguins)
library(tidyverse)
library(ggthemes)

ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm") +
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", y = "Body mass (g)",
    color = "Species", shape = "Species"
  ) +
  scale_color_colorblind()
```

Saving the last plot to disk can be done with \``ggsave("image.png")`.
